server {
    listen 80;
    server_name _;
    index index.html;

    # main page from repo root
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ =404;
    }

    # first folder -> /a/
    location /mk/ {
        alias /usr/share/nginx/mk/;
        try_files $uri $uri/ =404;
    }

    # second folder -> /b/
    location /prevod/ {
        alias /usr/share/nginx/prevod/;
        try_files $uri $uri/ =404;
    }
}
